### ISSUE TITLE
ReuseItemData这个类里的SetData示例方法是错误的。。。

### ISSUE THREAD

**Issue by ZJOnline** [LaiYizhou/Unity-ReuseScrollView#1]
这个是数据类，不用挂到物体上吧，看代码是new出来的，示例代码里操作text放到ReuseItem类里面才可以

**Comment by LaiYizhou** [comment]
嗯嗯，是的。但是我最初的想法是把SetData和ShowData分开，所以，把ReuseItemData.cs的SetData() 重新命名为 ShowData() 会好一点。后续我处理一下，thx.
